config/routes.rb
Rails.application.routes.draw do
  root 'documents#index'

  # user routes
  resources :users, only: %i[new create edit update show destroy]

  get '/share/private', to: 'documents#private_share'
  get '/share/', to: 'documents#share'
  get '/download', to: 'documents#download'
  resources :documents

  # session routes
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  delete '/sessions', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :permissions, dependent: :destroy
  has_many :documents, through: :permissions
  has_one :doc_file
  validates :file, presence: true, uniqueness: true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :document
  belongs_to :user

  scope :find_by_user_and_doc_id, ->(user_id, document_id) { find_by(user_id: user_id, document_id: document_id)}

  enum access: {
    owner: 0,
    guest: 1
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :permissions, dependent: :destroy
  has_many :documents, through: :permissions
  has_secure_password
  validates :username, presence: true, uniqueness: true, length: { maximum: 15 }
  validates :password, presence: true, length: { maximum: 20 }

  scope :get_user_docs_with_permission, lambda { |user, access|
                                          user.documents.where('permissions.access = ?', access)
                                        }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include ApplicationHelper
  include DocumentsHelper

  before_action :authorized, except: :download

  def index
    @documents = User.get_user_docs_with_permission(current_user, Permission.accesses['owner'])
    @rest_users = User.where.not(id: session[:user_id])
    @shared_documents = User.get_user_docs_with_permission(current_user, Permission.accesses['guest'])
  end

  def new
    @document = Document.new
  end

  def create
    @document = current_user.documents.new
    document_params = params[:document]
    @document.title = document_params[:title]
    @document.description = document_params[:description]
    input_file = document_params[:file]
    input_file_extension = File.extname(input_file.original_filename)
    @document.file = "#{@document.title}#{input_file_extension}"

    input_file_dir = Rails.root.join(path_to_file_dir)

    if @document.valid?

      if @document.save
        Dir.mkdir('uploads') unless Dir.exist?('uploads')
        Dir.mkdir(input_file_dir) unless Dir.exist?(input_file_dir)
        File.open(Rails.root.join(path_to_file(@document.file)), 'wb') do |file|
          file.write(input_file.read)
        end
        Permission.create(user: current_user, document: @document)
        redirect_to documents_url, notice: 'File uploaded successfully!'
      else
        render :new, status: :unprocessable_entity
      end

    else
      render :new, status: :unprocessable_entity, notice: 'File already exists'
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = current_user.documents.find(params[:id])
    update_params = documents_params
    old_file_name = update_params[:file]
    file_extension = File.extname(old_file_name)
    update_params[:file] = "#{update_params[:title]}#{file_extension}"

    File.open(path_to_file(old_file_name)) do |file|
      File.rename(file, path_to_file(update_params[:file]))
    end

    if @document.update(update_params)
      redirect_to documents_url, notice: 'File updated successfully!'
    else
      render :edit, status: :unprocessable_entity, notice: 'Something went wrong'
    end
  end

  def download
    permission = Permission.find_by_user_and_doc_id(session[:user_id], params[:id])
    document = Document.find(params[:id])
    document_owner_id = document.permissions.owner.pluck(:user_id).first
    if document&.public_share || permission
      send_file path_to_file(Rails.root.join(
                               'uploads', document_owner_id.to_s, document[:file]
                             )), x_sendfile: true
    else
      render file: 'public/404.html', status: :unauthorized
    end
  rescue ActiveRecord::RecordNotFound
    render file: 'public/404.html', status: :unauthorized
  end

  def share
    target_document = Document.find(params[:id])
    target_document.update(public_share: !target_document.public_share)
    redirect_to documents_url
  end

  def private_share
    user = User.find(params[:user_id])
    if params[:type] == 'share'
      document = Document.find(params[:id])
      redirect_to documents_url if Permission.create(user: user, document: document, access: :guest)
    else
      Permission.find_by_user_and_doc_id(params[:user_id], params[:id]).destroy
      redirect_to documents_url
    end
  end

  def destroy
    @document = current_user.documents.find(params[:id])
    file_name = @document.file
    File.delete(path_to_file(file_name)) if File.exist?(path_to_file_dir)
    if @document.destroy
      redirect_to documents_url, notice: 'File deleted successfully!'
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def documents_params
    params.require(:document).permit(:title, :description, :file, :id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login; end

  def create
    @user = User.find_by(username: params[:username])

    ## authenticate user credentials
    if @user && @user.authenticate(params[:password])
      # set session and redirect on success
      session[:user_id] = @user.id
      redirect_to documents_url
    else
      # error message on fail
      message = 'Make sure your username and password are correct.'
      redirect_to login_url, notice: message
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  before_action :authorized, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to documents_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if logged_in?
  end

  def authorized
    redirect_to login_url unless logged_in?
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def path_to_file_dir
    Rails.root.join('uploads', session[:user_id].to_s)
  end

  def path_to_file(file_name)
    Rails.root.join(path_to_file_dir, file_name)
  end
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title, required: true %>
  <%= form.label :description %>
  <%= form.text_field :description, required: true %>
  <% if type == 'new' %>
    <%= form.file_field :file, required: true %>
  <% else %>
    <%= form.text_field :file, hidden: true %>
  <% end %>
  <%= form.submit (type == 'new' ? "Upload document" : 'Update File'), class: "create-button" %>
<% end %>

app/views/documents/edit.html.erb
<% if @document.errors.any? %>
  <p class="notice notice__error"><%= @document.errors.full_messages[0] %> </p>
<%end%>
<div class="form">
  <h1 class="heading">Edit Your File</h1>
  <%= render 'form', document: @document, type: 'edit'%>
</div>

app/views/documents/index.html.erb
<h1 class="heading">My Files</h1>
<% if @documents.empty? %>
  <p>It feels so empty here!</p>
<% else %>
  <div class="documents-list">
    <span class="documents-list__title">Title</span>
    <span class="documents-list__title">Description</span>
    <span class="documents-list__title">Share Url</span>
    <span class="documents-list__title">Download</span>
    <span class="documents-list__title">Edit</span>
    <span class="documents-list__title">Delete</span>
    <% @documents.each do |doc| %>
      <span><%= doc.file %></span>
      <span><%= doc.description %></span>
      <% if doc.public_share %>
        <div >
          <%= button_to "Revoke Public Access" , share_path, params: { id: doc.id }, class: 'edit-button share-button', method: :get %>
          <span class="share-url"><%= "#{request.base_url}/download?id=#{doc.id}" %></span>
        </div>
      <% else %>
        <div >
          <%= button_to "Grant Public Access" , share_path, params: { id: doc.id }, class: 'edit-button share-button', method: :get %>
        </div>
      <% end %>
      <%= link_to "Download" , download_path(id: doc.id), method: :get %>
      <%= button_to "Edit" , edit_document_path(doc), class: 'edit-button', method: :get %>
      <%= button_to 'Delete', document_path(doc), method: :delete, class: 'delete-button' %>
      <div class="private-share">
        <span class="private-share__title">Private Share</span>
        <% @rest_users.each do |user|%>
          <div class="private-share__user">
            <% if user.documents.where(id: doc.id).empty?%>
              <div class="private-share__name private-share__name--share"><%= user.username%></div>
              <%= button_to 'Share',
                share_private_path,
                params: { id: doc.id, type: 'share', user_id: user.id },
                method: :get,
                class: 'private-share__button private-share__button--share'
              %>
            <% else %>
              <div class="private-share__name private-share__name--revoke"><%= user.username%></div>
              <%= button_to 'Revoke',
                share_private_path,
                params: { id: doc.id, type: 'revoke', user_id: user.id },
                method: :get,
                class: 'private-share__button private-share__button--revoke'
              %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<div class="shared-documents">
  <% if !@shared_documents.empty? %>
    <h1 class="heading">Files shared with me</h1>
    <div class="documents-list">
      <span class="documents-list__title">Title</span>
      <span class="documents-list__title">Description</span>
      <span class="documents-list__title">Download</span>
      <% @shared_documents.each do |doc| %>
        <span><%= doc.file %></span>
        <span><%= doc.description %></span>
        <%= link_to "Download" , download_path(id: doc.id), method: :get %>
      <% end %>
    </div>
  <% end %>
</div>
<br />
<br />
<%=button_to 'Add file', new_document_path, method: :get, class: 'create-button' %>

app/views/documents/new.html.erb
<% if @document.errors.any? %>
  <p class="notice notice__error"><%= @document.errors.full_messages[0] %> </p>
<%end%>
<div class="form">
  <h1 class="heading">Add Your File</h1>
  <%= render 'form', document: @document, type: 'new'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>File Manager</title>
  <%= favicon_link_tag asset_path('logo.png') %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <body>
    <header>
      <nav class="navbar">
        <div class="navbar__logo">
          <%= image_tag "logo.png"%>
          <span>Files Manager</span>
        </div>
        <% if current_user %>
          <div class="navbar__user">
            <span>Hi <%= current_user.username%></span>
            <% if logged_in? %>
              <%= button_to "Logout", sessions_path, method: :delete %>
            <% else %>
              <%= button_to "Login Page", login_path, method: :get %>
            <% end %>
          </div>
        <% end %>
      </nav>
      <% if notice %>
        <div class="nav__notice"><%= notice %></div>
      <% end %>
    </header>
    <main class="main">
      <%= yield %>
    </main>
    <br>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message|%>
    <h3><%= message %> </h3>
  <%end%>
<%end%>
<div class="form">
  <h1 class="heading">
    Signup
  </h1>
  <%= form_for @user do |form| %>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %><br />
    <%= form.label :password %>
    <%= form.password_field :password, required: true %><br />
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, placeholder: 'Confirm Password' ,required: true %><br />
    <%= form.submit "Create Account", class: "edit-button" %>
  <% end %>
  <div class="login-signup">
    <p>Changed my mind!</p>
    <%= button_to 'Back', login_path, method: :get, class: 'edit-button'%>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome to the page of <%= @user.username %></h1>
<% if current_user == @user %>
  <h3>This is my page!!!</h3>
<% end %>